# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f86851858167f42c36b1fc26b92a0a0400a0bcb34faf1fc3e9384a52bbd336ad94a896b9e6fad0e85d637b5a7930d0195fee87b32ce3fdef3356cc14c6bb90d7

test:
  secret_key_base: e59048b12b10f8e66d1665805fc013922afceda8a1ef4579c300c6c47f4868d0ad3409f4bcb8ffc3223ab04b6464b1c0a3a52deda3ade1cf9fed9b626a566c0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
